### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by davidhunter22** [heku/Kool.EditProject#2]
My most used extension! Any chance of a version for VS 2019?

**Comment by heku** [comment]
Thank you, I had added support for vs 2019 but not publish to marketplace yet, will do soon. It is appreciated if you could help test the lastest CI build on dev branch.

**Comment by davidhunter22** [comment]
Tried it out on VS 2019 RC2 works fine. Thanks

**Comment by heku** [comment]
Thank you for your feedback.
