### ISSUE TITLE
Not working correctly on VS2019 16.10.3

### ISSUE THREAD

**Issue by dcarapic** [heku/Kool.EditProject#3]
This is on a Visual Basic .NET 4.7.2 project:
- Editing the project works the first time (file is opened in visual studio text editor)
- Saving does not work (save does nothing)
- Once the editor is closed clicking on 'Edit project' does nothing

Note:
I would prefer that an external text editor (Notepad++ is on my side the default) would open instead. Perhaps you might add an option for this.

**Comment by heku** [comment]
Thanks for your feedback, I'll condiser your suggestion and try to see if I can add the external editor support soon.

**Comment by heku** [comment]
Hi @dcarapic 
The external editor support added, please update to latest extension then you can config it in Options | Kool | Edit Project.
Feel free to let me know if there's any issue.
